---
name: 'Build Wireguard Docker Image'
on:
  workflow_dispatch:
jobs:
  build:
    name: 'OCI'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/samerx
      image_name: wireguard      
